name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout AFL-automation
    - name: Get SDM
      run: curl -L https://raw.githubusercontent.com/gitbls/sdm/master/EZsdmInstaller | bash

    - name: Get RasPi base image
      run: curl -o raspios.img.xz https://downloads.raspberrypi.org//raspios_arm64/images/raspios_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64.img.xz

    - name: Unzip image
      run: xz -d raspios.img.xz 

    - name: Use SDM to provision image
      run: sudo sdm --customize --hostname:piloader --plugin user:"setpassword=afl|password=${{secrets.PI_PASSWORD}}" --plugin L10n:host --plugin disables:piwiz --plugin raspiconfig:"spi=1|serial=1|i2c=1|rgpio=1" --regen-ssh-host-keys --restart 2023-03-15-raspios-bookworm-arm64.img

    - name: Recompress image
      run: gzip raspios.img; mv raspios.img.gz piloader.img.gz
      
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/piloader.img.gz
        asset_name: piloader
        tag: ${{ github.ref }}
        overwrite: true
        body: "PiLoader full SD card image"
